---
# Copyright: (c) 2022, XLAB Steampunk <steampunk@xlab.si>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Check Subscription
  ansible.builtin.import_role:
    name: check_rhel_subscription

- name: Install Packages
  ansible.builtin.dnf:
    state: present
    name:
    - fdo-admin-cli
    - fdo-owner-onboarding-server
    - firewalld
    - sshpass
    - rsync

- name: Creates FDO Keys Directory
  ansible.builtin.file:
    path: "{{ fdo_src }}/keys"
    state: directory
    mode: "0775"

- name: Copy Device Certificates from Manufacturing Server
  ansible.posix.synchronize:
    src: "{{ manufacturing_server_fdo_src }}/keys/device_ca_cert.pem"
    dest: "{{ fdo_src }}/keys/device_ca_cert.pem"
    checksum: true
    rsync_timeout: 60
  delegate_to: "{{ manufacturing_server_url }}"
  when: copy_manufacturer_certs | bool

- name: Copy Owner Key from Manufacturing Server
  ansible.posix.synchronize:
    src: "{{ manufacturing_server_fdo_src }}/keys/owner_key.der"
    dest: "{{ fdo_src }}/keys/owner_key.der"
    checksum: true
    rsync_timeout: 60
  delegate_to: "{{ manufacturing_server_url }}"
  when: copy_manufacturer_certs | bool

- name: Copy Owner Certificate from Manufacturing Server
  ansible.posix.synchronize:
    src: "{{ manufacturing_server_fdo_src }}/keys/owner_cert.pem"
    dest: "{{ fdo_src }}/keys/owner_cert.pem"
    checksum: true
    rsync_timeout: 60
  delegate_to: "{{ manufacturing_server_url }}"
  when: copy_manufacturer_certs | bool

- name: Create Owner Service Keys Stores
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
    recurse: true
  loop:
  - "{{ fdo_src }}/stores/owner_vouchers"
  - "{{ fdo_src }}/stores/owner_onboarding_sessions"

- name: Copy Owner Onboarding Server Config
  ansible.builtin.copy:
    src: /usr/share/doc/fdo/owner-onboarding-server.yml
    dest: "{{ fdo_src }}/owner-onboarding-server.yml"
    mode: "0644"
    remote_src: true

- name: Copy ServiceInfo API Server Config
  ansible.builtin.copy:
    src: /usr/share/doc/fdo/serviceinfo-api-server.yml
    dest: "{{ fdo_src }}/serviceinfo-api-server.yml"
    mode: "0644"
    remote_src: true

- name: Start and Enable FDO Onboarding Server Service
  ansible.builtin.systemd:
    name: fdo-owner-onboarding-server
    state: started
    enabled: true

- name: Start and Enable FDO ServiceInfo API Server Service
  ansible.builtin.systemd:
    name: fdo-serviceinfo-api-server
    state: started
    enabled: true

- name: Start firewalld service
  ansible.builtin.service:
    name: firewalld
    state: started

- name: Open Required Ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
  - 8081/tcp
  - 8083/tcp
