---
# Copyright: (c) 2022, XLAB Steampunk <steampunk@xlab.si>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

### Create backup of existing configuration file and create a new one from template. ###
- name: Copy Old Manufacturing Server Config
  ansible.builtin.copy:
    src: "{{ fdo_src }}/manufacturing-server.yml"
    dest: "{{ fdo_src }}/manufacturing-server.yml.old"
    mode: "0644"
    remote_src: true

- name: Configure Manufacturing Server
  ansible.builtin.template:
    src: ../templates/manufacturing-server.yml.j2
    dest: "{{ fdo_src }}/manufacturing-server.yml"
    mode: "0644"
