---
# Copyright: (c) 2022, XLAB Steampunk <steampunk@xlab.si>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Update config file and restart FDO Manufacturing Server
  block:
    - name: Create backup of the old config file and create a new one from the template
      ansible.builtin.import_tasks: copy_config_file.yml

    - name: Restart FDO Manufacturing Server
      ansible.builtin.systemd:
        name: fdo-manufacturing-server
        state: restarted
        enabled: true

    - name: Check FDO Manufacturing Server Status
      ansible.builtin.systemd:
        name: fdo-manufacturing-server
      register: fdo_manufacturing_server_status

    - name: Report FDO Manufacturing Server Status
      ansible.builtin.fail:
        msg: FDO Manufacturing Server failed to restart after configuration change.
      when: fdo_manufacturing_server_status.status.ActiveState != 'active'

    - name: Open Required Ports
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - "{{ manufacturing_server_listen_port_manufacturing_server }}/tcp"

  rescue:
    - name: Reset config file
      ansible.builtin.import_tasks: reset_config_file.yml
      when: enable_roll_back | bool

    - name: Restart FDO Manufacturing Server
      ansible.builtin.systemd:
        name: fdo-manufacturing-server
        state: restarted
        enabled: true
      when: enable_roll_back | bool

    - name: FDO Manufacturing Server configuration failed
      ansible.builtin.fail:
        msg: FDO Manufacturing Server configuration failed.
