---
# Copyright: (c) 2022, XLAB Steampunk <steampunk@xlab.si>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

argument_specs:
  main:
    version_added: 1.0.0
    short_description: Setup the owner server
    description: 
      - Checks RHEL subscription and installs fdo-rendezvous-server package with dnf.
        Creates FDO keys directory, copies manufacturer certificate from manufacturing server and creates rendezvous service keys stores.
        It then copies the rendezvous server config example. starts and enables the FDO rendezvous server service and opens required ports.
    options:
      fdo_src:
        description:
          - Fdo directory path.
        type: str
        default: /etc/fdo
      manufacturing_server_fdo_src:
        description:
          - Fdo directory path on the manufacturing server.
        type: str
        default: /etc/fdo
      manufacturing_server_url:
        description:
          - Manufacturing Server URL.
        type: str
        default: "{{ groups['manufacturing_server'][0] }}"
      copy_manufacturer_certs:
        description:
          - Enable fetching manufacturing server certificates & keys.
        type: bool
        default: true
