---
# Copyright: (c) 2022, XLAB Steampunk <steampunk@xlab.si>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

### Create backups of existing configuration files and create new ones from templates. ###
- name: Copy Old AIO Config
  ansible.builtin.copy:
    src: "{{ fdo_aio_src }}/aio_configuration"
    dest: "{{ fdo_aio_src }}/aio_configuration.old"
    mode: "0644"
    remote_src: true

- name: Copy Old Manufacturing Server Config
  ansible.builtin.copy:
    src: "{{ fdo_aio_src }}/configs/manufacturing_server.yml"
    dest: "{{ fdo_aio_src }}/configs/manufacturing_server.yml.old"
    mode: "0644"
    remote_src: true

- name: Copy Old Rendezvous Server Config
  ansible.builtin.copy:
    src: "{{ fdo_aio_src }}/configs/rendezvous_server.yml"
    dest: "{{ fdo_aio_src }}/configs/rendezvous_server.yml.old"
    mode: "0644"
    remote_src: true

- name: Copy Old Owner Onboarding Server Config
  ansible.builtin.copy:
    src: "{{ fdo_aio_src }}/configs/owner_onboarding_server.yml"
    dest: "{{ fdo_aio_src }}/configs/owner_onboarding_server.yml.old"
    mode: "0644"
    remote_src: true

- name: Copy Old ServiceInfo API Server Config
  ansible.builtin.copy:
    src: "{{ fdo_aio_src }}/configs/serviceinfo_api_server.yml"
    dest: "{{ fdo_aio_src }}/configs/serviceinfo_api_server.yml.old"
    mode: "0644"
    remote_src: true

- name: Configure AIO
  ansible.builtin.template:
    src: "{{ role_path }}/templates/aio_configuration.j2"
    dest: "{{ fdo_aio_src }}/aio_configuration"
    mode: "0644"
  register: aio_configuration

- name: Configure Manufacturing Server
  ansible.builtin.template:
    src: "{{ role_path }}/templates/manufacturing_server.yml.j2"
    dest: "{{ fdo_aio_src }}/configs/manufacturing_server.yml"
    mode: "0644"
  register: manufacturing_server

- name: Configure Rendezvous Server
  ansible.builtin.template:
    src: "{{ role_path }}/templates/rendezvous_server.yml.j2"
    dest: "{{ fdo_aio_src }}/configs/rendezvous_server.yml"
    mode: "0644"
  register: rendezvous_server

- name: Configure Owner Onboarding Server
  ansible.builtin.template:
    src: "{{ role_path }}/templates/owner_onboarding_server.yml.j2"
    dest: "{{ fdo_aio_src }}/configs/owner_onboarding_server.yml"
    mode: "0644"
  register: owner_onboarding_server

- name: Configure ServiceInfo API Server
  ansible.builtin.template:
    src: "{{ role_path }}/templates/serviceinfo_api_server.yml.j2"
    dest: "{{ fdo_aio_src }}/configs/serviceinfo_api_server.yml"
    mode: "0644"
  register: owner_onboarding_server
