---
# Copyright: (c) 2022, XLAB Steampunk <steampunk@xlab.si>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

### Create backups of existing configuration files and create new ones from templates. ###
- name: Copy Old AIO Config
  copy:
    src: "{{ fdo_aio_src }}/aio_configuration"
    dest: "{{ fdo_aio_src }}/aio_configuration.old"
    remote_src: yes

- name: Copy Old Manufacturing Server Config
  copy:
    src: "{{ fdo_aio_src }}/configs/manufacturing_server.yml"
    dest: "{{ fdo_aio_src }}/configs/manufacturing_server.yml.old"
    remote_src: yes

- name: Copy Old Rendezvous Server Config
  copy:
    src: "{{ fdo_aio_src }}/configs/rendezvous_server.yml"
    dest: "{{ fdo_aio_src }}/configs/rendezvous_server.yml.old"
    remote_src: yes

- name: Copy Old Owner Onboarding Server Config
  copy:
    src: "{{ fdo_aio_src }}/configs/owner_onboarding_server.yml"
    dest: "{{ fdo_aio_src }}/configs/owner_onboarding_server.yml.old"
    remote_src: yes

- name: Copy Old ServiceInfo API Server Config
  copy:
    src: "{{ fdo_aio_src }}/configs/serviceinfo_api_server.yml"
    dest: "{{ fdo_aio_src }}/configs/serviceinfo_api_server.yml.old"
    remote_src: yes

- name: Configure AIO
  template:
    src: ../templates/aio_configuration.j2
    dest: "{{ fdo_aio_src }}/aio_configuration"
  register: aio_configuration

- name: Configure Manufacturing Server
  template:
    src: ../templates/manufacturing_server.yml.j2
    dest: "{{ fdo_aio_src }}/configs/manufacturing_server.yml"
  register: manufacturing_server

- name: Configure Rendezvous Server
  template:
    src: ../templates/rendezvous_server.yml.j2
    dest: "{{ fdo_aio_src }}/configs/rendezvous_server.yml"
  register: rendezvous_server

- name: Configure Owner Onboarding Server
  template:
    src: ../templates/owner_onboarding_server.yml.j2
    dest: "{{ fdo_aio_src }}/configs/owner_onboarding_server.yml"
  register: owner_onboarding_server

- name: Configure ServiceInfo API Server
  template:
    src: ../templates/serviceinfo_api_server.yml.j2
    dest: "{{ fdo_aio_src }}/configs/serviceinfo_api_server.yml"
  register: owner_onboarding_server
