---
# Copyright: (c) 2022, XLAB Steampunk <steampunk@xlab.si>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Update config files and restart FDO AIO service
  block:
    - name: Create backups of old config files and create new ones from templates
      import_tasks: copy_config_files.yml

    - name: Restart FDO AIO Service
      systemd:
        name: fdo-aio
        state: restarted
        enabled: yes

    - name: Check FDO AIO Service Status
      command: systemctl status fdo-aio
      register: service_fdo_aio_status

    - name: Report Status of FDO AIO Service
      fail:
        msg: FDO AIO Service failed to restart after configuration change.
      when: service_fdo_aio_status.rc != 0

    - name: Open Required Ports
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: true
      loop:
        - "{{ aio_configuration_listen_port_manufacturing_server }}/tcp"
        - "{{ aio_configuration_listen_port_owner_onboarding_server }}/tcp"
        - "{{ aio_configuration_listen_port_rendezvous_server }}/tcp"
        - "{{ aio_configuration_listen_port_serviceinfo_api_server }}/tcp"

  rescue:
    - name: Reset config files
      import_tasks: reset_config_files.yml
      when: enable_roll_back | bool == true

    - name: Restart FDO AIO Service
      systemd:
        name: fdo-aio
        state: restarted
        enabled: yes
      when: enable_roll_back | bool == true

    - name: FDO AIO Service configuration failed
      fail:
        msg: FDO AIO Service configuration failed.
