---
# Copyright: (c) 2022, XLAB Steampunk <steampunk@xlab.si>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Check Subscription
  ansible.builtin.import_role:
    name: check_rhel_subscription

- name: Install Packages
  ansible.builtin.dnf:
    state: latest
    name:
    - fdo-admin-cli
    - fdo-manufacturing-server
    - firewalld
    - sshpass
    - rsync

- name: Creates FDO Keys Directory
  ansible.builtin.file:
    path: "{{ fdo_src }}/keys"
    state: directory
    mode: "0775"

- name: Check if Certs and Keys folder is empty before proceeding
  ansible.builtin.find:
    paths: "{{ fdo_src }}/keys"
  register: files_found

- name: Generate new FDO Certs and Keys
  ansible.builtin.shell: |
    for i in manufacturer owner device-ca diun ; do

    fdo-admin-tool generate-key-and-cert \
    --destination-dir "{{ fdo_src }}/keys" $i

    done
  when: files_found.matched == 0
  changed_when: true # assume always (re-)generates when called

- name: Create Manufacturer Service Keys Stores
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
    recurse: true
  loop:
  - "{{ fdo_src }}/stores/manufacturer_keys"
  - "{{ fdo_src }}/stores/manufacturing_sessions"
  - "{{ fdo_src }}/stores/owner_vouchers"

- name: Copy Manufacturing Server Config
  ansible.builtin.copy:
    src: /usr/share/doc/fdo/manufacturing-server.yml
    dest: "{{ fdo_src }}/manufacturing-server.yml"
    mode: "0644"
    remote_src: true

- name: Start and Enable FDO Manufacturing Server Service
  ansible.builtin.systemd:
    name: fdo-manufacturing-server
    state: started
    enabled: true

- name: Start firewalld service
  ansible.builtin.service:
    name: firewalld
    state: started

- name: Open Required Ports
  ansible.posix.firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
    immediate: true
