---
namespace: community
name: fdo
version: 1.0.0
readme: README.md
authors:
  - XLAB Steampunk <steampunk@xlab.si>
description: FDO components installation and configuration
license:
  - GPL-3.0-or-later
license_file: LICENSE
tags: 
  - fdo
  - fido
  - device_onboarding
dependencies: 
  - ansible.posix: '*'
repository: https://github.com/ansible-collections/community.fdo
documentation: https://github.com/ansible-collections/community.fdo/blob/main/examples/README.md
homepage: https://github.com/ansible-collections/community.fdo
issues: https://github.com/ansible-collections/community.fdo/issues
build_ignore:
- .idea
- .gitignore
- .flake8
- DEVELOPMENT.md
- DEV-github-runner.md
- Makefile
- sanity.requirements
- test.requirements
- tests
# files used during local testing/building
- ansible.cfg
- sample*
