---
# Copyright: (c) 2022, XLAB Steampunk <steampunk@xlab.si>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- ansible.builtin.import_role:
    name: check_rhel_subscription

- name: Install Packages
  ansible.builtin.dnf:
    state: latest
    name:
    - fdo-admin-cli
    - firewalld

- name: Start and Enable FDO AIO Service
  ansible.builtin.systemd:
    name: fdo-aio
    state: started
    enabled: true

- name: Start firewalld service
  ansible.builtin.service:
    name: firewalld
    state: started

- name: Open Required Ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
  - 8080/tcp
  - 8081/tcp
  - 8082/tcp
  - 8083/tcp
