---
# configuration settings
fdo_aio_src: /etc/fdo/aio
enable_roll_back: true

# aio_configuration
aio_configuration_cert_organization: FDO AIO
aio_configuration_cert_country: US
aio_configuration_listen_ip_address: 0.0.0.0
aio_configuration_listen_port_manufacturing_server: 8080
aio_configuration_listen_port_owner_onboarding_server: 8081
aio_configuration_listen_port_rendezvous_server: 8082
aio_configuration_listen_port_serviceinfo_api_server: 8083
aio_configuration_separate_manufacturing_and_owner_voucher_store: false
aio_configuration_manufacturing_enable_plain_di: false
aio_configuration_manufacturing_disable_key_storage_filesystem: false
aio_configuration_manufacturing_disable_key_storage_tpm: false
aio_configuration_manufacturing_use_secp256r1: false
aio_configuration_contact_hostname: ~
aio_configuration_contact_addresses_IpAddr: "{{ ansible_default_ipv4.address }}" # Must be either set manually (if you system has more than one interface) or used with `gather_facts: true` in your playbook.
#aio_configuration_serviceinfo_api_auth_token: TestAuthToken # change to a valid API token
#aio_configuration_serviceinfo_api_admin_token: TestAdminToken # change to a valid API token

# manufacturing_server.yml
manufacturing_server_session_store_driver_path: "{{ fdo_aio_src }}/stores/manufacturing_sessions"
manufacturing_server_ownership_voucher_store_driver_path: "{{ fdo_aio_src }}/stores/owner_vouchers"
manufacturing_server_public_key_store_driver_path: "{{ fdo_aio_src }}/stores/manufacturer_keys"
manufacturing_server_protocols_plain_di: false
manufacturing_server_protocols_key_path: "{{ fdo_aio_src }}/keys/diun_key.der"
manufacturing_server_protocols_cert_path: "{{ fdo_aio_src }}/keys/diun_cert.pem"
manufacturing_server_rendezvous_info_protocol: http
manufacturing_server_manufacturer_cert_path: "{{ fdo_aio_src }}/keys/manufacturer_cert.pem"
manufacturing_server_device_cert_ca_private_key: "{{ fdo_aio_src }}/keys/device_ca_key.der"
manufacturing_server_device_cert_ca_chain: "{{ fdo_aio_src }}/keys/device_ca_cert.pem"
manufacturing_server_owner_cert_path: "{{ fdo_aio_src }}/keys/owner_cert.pem"
manufacturing_server_manufacturer_private_key: "{{ fdo_aio_src }}/keys/manufacturer_key.der"

# rendezvous_server.yml
rendezvous_server_storage_driver_path: "{{ fdo_aio_src }}/stores/rendezvous_registered"
rendezvous_server_session_store_driver_path: "{{ fdo_aio_src }}/stores/rendezvous_sessions"
rendezvous_server_trusted_manufacturer_keys_path: "{{ manufacturing_server_manufacturer_cert_path }}"
rendezvous_server_max_wait_seconds: ~

# owner_onboarding_server.yml
owner_onboarding_server_ownership_voucher_store_driver_path: "{{ manufacturing_server_ownership_voucher_store_driver_path }}"
owner_onboarding_server_session_store_driver_path: "{{ fdo_aio_src }}/stores/owner_onboarding_sessions"
owner_onboarding_server_trusted_device_keys_path: "{{ manufacturing_server_device_cert_ca_chain }}"
owner_onboarding_server_owner_private_key_path: "{{ fdo_aio_src }}/keys/owner_key.der"
owner_onboarding_server_owner_public_key_path: "{{ manufacturing_server_owner_cert_path }}"
owner_onboarding_server_service_info_api_authentication_token: "{{ aio_configuration_serviceinfo_api_auth_token }}"
owner_onboarding_server_owner_addresses_transport: http
owner_onboarding_server_report_to_rendezvous_endpoint_enabled: true

# serviceinfo_api_server.yml
serviceinfo_api_server_service_info_initial_user: ~
serviceinfo_api_server_service_info_files: ~
serviceinfo_api_server_service_info_commands: ~
serviceinfo_api_server_service_info_diskencryption_clevis: ~
serviceinfo_api_server_service_info_additional_serviceinfo: ~
serviceinfo_api_server_device_specific_store_driver_path: "{{ fdo_aio_src }}/stores/serviceinfo_api_devices"
