---
# Copyright: (c) 2022, XLAB Steampunk <steampunk@xlab.si>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

argument_specs:
  main:
    version_added: 1.0.0
    short_description: Setup the manufacturing server
    description: 
      - Checks RHEL subscription and installs fdo-admin-cli and fdo-manufacturing-server packages with dnf.
        Creates an FDO keys directory, checks if it is empty and generates keys and certificates inside it using fdo-admin-tool.
        Then creates manufacturer service key storages, copies the manufacturing server config example, starts and enables the
        FDO manufacturing server service and opens the required ports.
    options:
      fdo_src:
        description:
          - Fdo directory path.
        type: str
        default: /etc/fdo
