---
# Copyright: (c) 2022, XLAB Steampunk <steampunk@xlab.si>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Check Subscription
  ansible.builtin.import_role:
    name: check_rhel_subscription

- name: Install Packages
  ansible.builtin.dnf:
    state: present
    name:
      - fdo-rendezvous-server
      - firewalld
      - sshpass
      - rsync

- name: Creates FDO Keys Directory
  ansible.builtin.file:
    path: "{{ fdo_src }}/keys"
    state: directory
    mode: "0775"

- name: Copy Manufacturer Certificate from Manufacturing Server
  ansible.posix.synchronize:
    src: "{{ manufacturing_server_fdo_src }}/keys/manufacturer_cert.pem"
    dest: "{{ fdo_src }}/keys/manufacturer_cert.pem"
    checksum: true
    rsync_timeout: 60
  delegate_to: "{{ manufacturing_server_url }}"
  when: copy_manufacturer_certs | bool

- name: Create Rendezvous Service Keys Stores
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
    recurse: true
  loop:
    - "{{ fdo_src }}/stores/rendezvous_registered"
    - "{{ fdo_src }}/stores/rendezvous_sessions"

- name: Copy Rendezvous Server Config
  ansible.builtin.copy:
    src: /usr/share/doc/fdo/rendezvous-server.yml
    dest: "{{ fdo_src }}/rendezvous-server.yml"
    mode: "0644"
    remote_src: true

- name: Start and Enable FDO Rendezvous Server Service
  ansible.builtin.systemd:
    name: fdo-rendezvous-server
    state: started
    enabled: true

- name: Start firewalld service
  ansible.builtin.service:
    name: firewalld
    state: started

- name: Open Required Ports
  ansible.posix.firewalld:
    port: 8082/tcp
    permanent: true
    state: enabled
    immediate: true
