---
# Copyright: (c) 2022, XLAB Steampunk <steampunk@xlab.si>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Update config files and restart FDO Servers
  block:
    - name: Create backups of old config files and create new ones from templates
      import_tasks: copy_config_files.yml

    - name: Update Manufacturing Server keys & certificates
      import_tasks: update_keys_certs.yml
      when: update_keys_certs | bool == true

    - name: Restart Owner Onboarding Server
      systemd:
        name: fdo-owner-onboarding-server
        state: restarted
        enabled: yes

    - name: Check Owner Onboarding Server Status
      command: systemctl status fdo-owner-onboarding-server
      register: fdo_rendezvous_server_status

    - name: Report Owner Onboarding Server Status
      fail:
        msg: Owner Onboarding Server failed to restart after configuration change.
      when: fdo_rendezvous_server_status.rc != 0

    - name: Restart Serviceinfo API Server
      systemd:
        name: fdo-serviceinfo-api-server
        state: restarted
        enabled: yes

    - name: Check Serviceinfo API Server Status
      command: systemctl status fdo-owner-onboarding-server
      register: fdo_serviceinfo_api_server_status

    - name: Report Serviceinfo API Server Status
      fail:
        msg: Serviceinfo API Server failed to restart after configuration change.
      when: fdo_serviceinfo_api_server_status.rc != 0

    - name: Open Required Ports
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: true
      loop:
        - "{{ owner_onboarding_server_listen_port_owner_onboarding_server }}/tcp"
        - "{{ owner_onboarding_server_listen_port_serviceinfo_api_server }}/tcp"

  rescue:
    - name: Reset config file
      import_tasks: reset_config_file.yml
      when: enable_roll_back | bool == true

    - name: Restart Owner Onboarding Server
      systemd:
        name: fdo-owner-onboarding-server
        state: restarted
        enabled: yes
      when: enable_roll_back | bool == true

    - name: Restart Serviceinfo API Server
      systemd:
        name: fdo-serviceinfo-api-server
        state: restarted
        enabled: yes
      when: enable_roll_back | bool == true

    - name: FDO Owner Onboarding & Serviceinfo API Servers configuration failed
      fail:
        msg: FDO Owner Onboarding & Serviceinfo API Servers configuration failed.
