---
# Copyright: (c) 2022, XLAB Steampunk <steampunk@xlab.si>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

### Updates Manufacturing Server Device/Owner keys/certificates. ###
- name: Copy Device Certificates from Manufacturing Server
  synchronize:
    src: "{{ manufacturing_server_fdo_src }}/keys/device_ca_cert.pem"
    dest: "{{ fdo_src }}/keys/device_ca_cert.pem"
    checksum: true
    rsync_timeout: 60
  delegate_to: "{{ manufacturing_server_url }}"

- name: Copy Owner Key from Manufacturing Server
  synchronize:
    src: "{{ manufacturing_server_fdo_src }}/keys/owner_key.der"
    dest: "{{ fdo_src }}/keys/owner_key.der"
    checksum: true
    rsync_timeout: 60
  delegate_to: "{{ manufacturing_server_url }}"

- name: Copy Owner Certificate from Manufacturing Server
  synchronize:
    src: "{{ manufacturing_server_fdo_src }}/keys/owner_cert.pem"
    dest: "{{ fdo_src }}/keys/owner_cert.pem"
    checksum: true
    rsync_timeout: 60
  delegate_to: "{{ manufacturing_server_url }}"
