---
# Copyright: (c) 2022, XLAB Steampunk <steampunk@xlab.si>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

argument_specs:
  main:
    version_added: 1.0.0
    short_description: Setup AIO server
    description:
      - Checks RHEL subscription, installs fdo-admin-cli package with dnf, starts and enables the FDO AIO service
        and then opens the required ports.
