# Per https://www.ansible.com/blog/ansible-linting-with-github-actions
name: Run ansible-lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint Ansible Roles
      uses: ansible/ansible-lint-action@v6
      with:
        path: "./roles"
